### ISSUE TITLE
purpur버킷에서 prismarine으로 바꿨더니 크래쉬가 떴습니다

### ISSUE THREAD

**Issue by Yahumoo** [PrismarineTeam/Prismarine#2]
[crash-2022-02-15_01.51.25-server.txt](https://github.com/PrismarineTeam/Prismarine/files/8062539/crash-2022-02-15_01.51.25-server.txt)

버전은 최신버전입니다. 서버가 열리지 않아서 정확히 확인은 못하겠어요

**Comment by AlphaKR93** [comment]
플러그인을 모두 빼더라도 똑같은 오류가 발생하나요?

**Comment by Yahumoo** [comment]
답장이 늦어져서 죄송합니다 플러그인 모두 빼고 열어봤는데도 RPG1이라는 맵을 열때 크래쉬가 뜨면서 서버가 안열리네요

**Comment by Yahumoo** [comment]
버전은 프리즈머린 101번째 릴리즈입니다
[crash-2022-02-18_05.25.01-server.txt](https://github.com/PrismarineTeam/Prismarine/files/8091981/crash-2022-02-18_05.25.01-server.txt)

**Comment by AlphaKR93** [comment]
청크 로드중 발생한 문제 같아요. 혹시 RPG1 월드를 보내주실수 있을까요?

**Comment by Yahumoo** [comment]
https://drive.google.com/file/d/1ff7j9a-yRG1g0OPQBFQndEPMgKwQbYjA/view?usp=sharing
깃허브에 안올라가서 구글 드라이브 링크 드립니다

**Comment by AlphaKR93** [comment]
@Yahumoo 님, 늦게 답변 드려 죄송합니다. 최신 버전의 Prismarine 버킷에서 문제가 발생하지 않음을 확인했습니다. 업데이트를 하더라도 계속 문제가 발생할경우 알려주세요. 감사합니다.
